name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the zsh-config are you running?
      placeholder: v1.1.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Other Linux
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: shell
    attributes:
      label: Shell Version
      description: What ZSH version are you using?
      options:
        - ZSH 5.9
        - ZSH 5.8
        - ZSH 5.7
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Open new terminal
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true